export const ENEMY_CONFIG = {
    basic: {
        radius: 12,
        speed: 50,
        health: 50,
        damage: 20,
        color: '#ff4444',
        scoreValue: 10,
        xpValue: 10,
    },
    fast: {
        radius: 8,
        speed: 120,
        health: 25,
        damage: 15,
        color: '#ff8844',
        scoreValue: 15,
        xpValue: 20,
    },
    tank: {
        radius: 18,
        speed: 25,
        health: 150,
        damage: 35,
        color: '#884444',
        scoreValue: 25,
        xpValue: 40,
    },
    shooter: {
        radius: 10,
        speed: 30,
        health: 40,
        damage: 15,
        color: '#ff4488',
        scoreValue: 20,
        lastShot: 0,
        shootCooldown: 2000,
        shootRange: 200,
        xpValue: 30,
    },
    exploder: {
        radius: 14,
        speed: 80,
        health: 30,
        damage: 50,
        color: '#ff44ff',
        scoreValue: 30,
        explosionRadius: 60,
        isExploding: false,
        explosionTimer: 0,
        explosionDuration: 500,
        xpValue: 35,
    },
};
